export type TrackDefinition = {
  id: string;
  genre: 'chill' | 'fantasy' | 'japanese';
  title: string;
  fileName: string;
};

export type Track = TrackDefinition & {
  source: string;
};

export const TRACK_DEFINITIONS: readonly TrackDefinition[] = [
  { id: 'track-01', title: 'Quiet Motion', genre: 'chill', fileName: '001_Quiet_Motion_v2_96BPM.mp3' },
  { id: 'track-02', title: 'Music Box Stroll', genre: 'chill', fileName: '002_Music_Box_Stroll_v4_MusicBox005_84BPM.mp3' },
  { id: 'track-03', title: 'Moonlit Waterside Room', genre: 'chill', fileName: '003_Moonlit_Waterside_Room_v6_77BPM.mp3' },
  { id: 'track-04', title: 'Variant A Six Eight Nocturne', genre: 'chill', fileName: '004_Variant_A_SixEight_Nocturne_72BPM.mp3' },
  { id: 'track-05', title: 'Variant D Night Waltz', genre: 'chill', fileName: '005_Variant_D_Night_Waltz_90BPM.mp3' },
  { id: 'track-06', title: 'Still Lake Morning', genre: 'chill', fileName: '006_Still_Lake_Morning.mp3' },
  { id: 'track-07', title: 'Coffee by the Window', genre: 'chill', fileName: '007_Coffee_by_the_Window.mp3' },
  { id: 'track-08', title: 'Blanket and Blue Sky', genre: 'chill', fileName: '008_Blanket_and_Blue_Sky.mp3' },
  { id: 'track-09', title: 'Quiet Ripples', genre: 'chill', fileName: '009_Quiet_Ripples.mp3' },
  { id: 'track-10', title: 'Slow Sunday Light', genre: 'chill', fileName: '010_Slow_Sunday_Light.mp3' },
  { id: 'track-11', title: 'Pillow-side Daydream', genre: 'chill', fileName: '011_Pillow-side_Daydream.mp3' },
  { id: 'track-12', title: 'Cedar Cabin Coffee', genre: 'chill', fileName: '012_Cedar_Cabin_Coffee.mp3' },
  { id: 'track-13', title: 'Clouds Over the Lake', genre: 'chill', fileName: '013_Clouds_Over_the_Lake.mp3' },
  { id: 'track-14', title: 'Afternoon Stillness', genre: 'chill', fileName: '014_Afternoon_Stillness.mp3' },
  { id: 'track-15', title: 'Dusk in Soft Blue', genre: 'chill', fileName: '015_Dusk_in_Soft_Blue.mp3' },
  { id: 'track-46', title: 'Morning Unfolds on the Lake', genre: 'chill', fileName: '046_Morning_Unfolds_on_the_Lake.mp3' },
  { id: 'track-47', title: 'White Cup by the Water', genre: 'chill', fileName: '047_White_Cup_by_the_Water.mp3' },
  { id: 'track-48', title: 'Lake Light through Linen', genre: 'chill', fileName: '048_Lake_Light_through_Linen.mp3' },
  { id: 'track-49', title: 'Still Water Soft Echoes', genre: 'chill', fileName: '049_Still_Water_Soft_Echoes.mp3' },
  { id: 'track-50', title: 'Until the Coffee Cools', genre: 'chill', fileName: '050_Until_the_Coffee_Cools.mp3' },
  { id: 'track-51', title: 'Waterside Reverie', genre: 'chill', fileName: '051_Waterside_Reverie.mp3' },
  { id: 'track-52', title: 'Waltz of Ripples', genre: 'chill', fileName: '052_Waltz_of_Ripples.mp3' },
  { id: 'track-53', title: 'Window at Dusk', genre: 'chill', fileName: '053_Window_at_Dusk.mp3' },
  { id: 'track-54', title: 'Blanket of Pale Light', genre: 'chill', fileName: '054_Blanket_of_Pale_Light.mp3' },
  { id: 'track-55', title: 'Reading by the Shore', genre: 'chill', fileName: '055_Reading_by_the_Shore.mp3' },
  { id: 'track-56', title: 'Curtains in the Afternoon', genre: 'chill', fileName: '056_Curtains_in_the_Afternoon.mp3' },
  { id: 'track-57', title: 'Blue Bookmark', genre: 'chill', fileName: '057_Blue_Bookmark.mp3' },
  { id: 'track-58', title: 'Waterside Tea', genre: 'chill', fileName: '058_Waterside_Tea.mp3' },
  { id: 'track-59', title: 'Time in the Shade', genre: 'chill', fileName: '059_Time_in_the_Shade.mp3' },
  { id: 'track-60', title: 'Two Cups', genre: 'chill', fileName: '060_Two_Cups.mp3' },
  { id: 'track-61', title: 'Dew Colored Lake', genre: 'chill', fileName: '061_Dew_Colored_Lake.mp3' },
  { id: 'track-62', title: 'Little Afternoon Pier', genre: 'chill', fileName: '062_Little_Afternoon_Pier.mp3' },
  { id: 'track-63', title: 'Drowsy Pages', genre: 'chill', fileName: '063_Drowsy_Pages.mp3' },
  { id: 'track-64', title: 'Amber Water', genre: 'chill', fileName: '064_Amber_Water.mp3' },
  { id: 'track-65', title: 'Lights Across the Lake', genre: 'chill', fileName: '065_Lights_Across_the_Lake.mp3' },
  { id: 'track-16', title: 'Sunlit Stone Avenue', genre: 'fantasy', fileName: '016_Sunlit_Stone_Avenue_90BPM.mp3' },
  { id: 'track-17', title: 'Arcane Bell Tower', genre: 'fantasy', fileName: '017_Arcane_Bell_Tower_84BPM.mp3' },
  { id: 'track-18', title: 'Willowmere Harbor', genre: 'fantasy', fileName: '018_Willowmere_Harbor_86BPM.mp3' },
  { id: 'track-19', title: 'Lanterns of the Old Market', genre: 'fantasy', fileName: '019_Lanterns_of_the_Old_Market_94BPM.mp3' },
  { id: 'track-20', title: 'Emerald Chapel Garden', genre: 'fantasy', fileName: '020_Emerald_Chapel_Garden_76BPM.mp3' },
  { id: 'track-21', title: 'Moonwell Academy', genre: 'fantasy', fileName: '021_Moonwell_Academy_82BPM.mp3' },
  { id: 'track-22', title: 'Rivergate Morning', genre: 'fantasy', fileName: '022_Rivergate_Morning_92BPM.mp3' },
  { id: 'track-23', title: 'Mistwood Village', genre: 'fantasy', fileName: '023_Mistwood_Village_78BPM.mp3' },
  { id: 'track-24', title: 'Starlit Alchemist Quarter', genre: 'fantasy', fileName: '024_Starlit_Alchemist_Quarter_88BPM.mp3' },
  { id: 'track-25', title: 'Golden Fountain Plaza', genre: 'fantasy', fileName: '025_Golden_Fountain_Plaza_96BPM.mp3' },
  { id: 'track-26', title: 'Whispering Library', genre: 'fantasy', fileName: '026_Whispering_Library_72BPM.mp3' },
  { id: 'track-27', title: 'Rosebridge Festival', genre: 'fantasy', fileName: '027_Rosebridge_Festival_102BPM.mp3' },
  { id: 'track-28', title: 'Silverleaf Outskirts', genre: 'fantasy', fileName: '028_Silverleaf_Outskirts_80BPM.mp3' },
  { id: 'track-29', title: 'Twilight Clockwork Lane', genre: 'fantasy', fileName: '029_Twilight_Clockwork_Lane_91BPM.mp3' },
  { id: 'track-30', title: 'Homeward Through the Gates', genre: 'fantasy', fileName: '030_Homeward_Through_the_Gates_86BPM.mp3' },
  { id: 'track-66', title: 'Starlit Magic Garden', genre: 'fantasy', fileName: '066_Starlit_Magic_Garden.mp3' },
  { id: 'track-67', title: 'Moonlit Cobblestones', genre: 'fantasy', fileName: '067_Moonlit_Cobblestones.mp3' },
  { id: 'track-68', title: 'Lullaby of the Magic Library', genre: 'fantasy', fileName: '068_Lullaby_of_the_Magic_Library.mp3' },
  { id: 'track-69', title: 'Poem of the Old Courtyard', genre: 'fantasy', fileName: '069_Poem_of_the_Old_Courtyard.mp3' },
  { id: 'track-70', title: 'Quiet Night at the Observatory', genre: 'fantasy', fileName: '070_Quiet_Night_at_the_Observatory.mp3' },
  { id: 'track-71', title: 'Town of Weather Vanes', genre: 'fantasy', fileName: '071_Town_of_Weather_Vanes.mp3' },
  { id: 'track-72', title: 'Dream of the Lantern Canal', genre: 'fantasy', fileName: '072_Dream_of_the_Lantern_Canal.mp3' },
  { id: 'track-73', title: 'Evening Sky by the Clocktower', genre: 'fantasy', fileName: '073_Evening_Sky_by_the_Clocktower.mp3' },
  { id: 'track-74', title: 'Crystal Greenhouse', genre: 'fantasy', fileName: '074_Crystal_Greenhouse.mp3' },
  { id: 'track-75', title: 'Rooftop Garden Magic', genre: 'fantasy', fileName: '075_Rooftop_Garden_Magic.mp3' },
  { id: 'track-76', title: 'Lantern Makers Workshop', genre: 'fantasy', fileName: '076_Lantern_Makers_Workshop.mp3' },
  { id: 'track-77', title: 'Old Bridge to the Stars', genre: 'fantasy', fileName: '077_Old_Bridge_to_the_Stars.mp3' },
  { id: 'track-78', title: 'Rest in the Herb Garden', genre: 'fantasy', fileName: '078_Rest_in_the_Herb_Garden.mp3' },
  { id: 'track-79', title: 'Riverside Bookshop', genre: 'fantasy', fileName: '079_Riverside_Bookshop.mp3' },
  { id: 'track-80', title: 'Moonlit Glass Arcade', genre: 'fantasy', fileName: '080_Moonlit_Glass_Arcade.mp3' },
  { id: 'track-81', title: 'Warmth of the Little Courtyard', genre: 'fantasy', fileName: '081_Warmth_of_the_Little_Courtyard.mp3' },
  { id: 'track-82', title: 'Afternoon in the Sky Garden', genre: 'fantasy', fileName: '082_Afternoon_in_the_Sky_Garden.mp3' },
  { id: 'track-83', title: 'Candles and Star Maps', genre: 'fantasy', fileName: '083_Candles_and_Star_Maps.mp3' },
  { id: 'track-84', title: 'Moonlit Flower Market', genre: 'fantasy', fileName: '084_Moonlit_Flower_Market.mp3' },
  { id: 'track-85', title: 'Dawn over the Magic City', genre: 'fantasy', fileName: '085_Dawn_over_the_Magic_City.mp3' },
  { id: 'track-31', title: 'Moonlit Shrine Reverie', genre: 'japanese', fileName: '031_Moonlit_Shrine_Reverie.mp3' },
  { id: 'track-32', title: 'Bamboo Flute Moon', genre: 'japanese', fileName: '032_Bamboo_Flute_Moon.mp3' },
  { id: 'track-33', title: 'Lantern Path Under the Full Moon', genre: 'japanese', fileName: '033_Lantern_Path_Under_the_Full_Moon.mp3' },
  { id: 'track-34', title: 'Moon on Temple Water', genre: 'japanese', fileName: '034_Moon_on_Temple_Water.mp3' },
  { id: 'track-35', title: 'Midnight Torii Shamisen', genre: 'japanese', fileName: '035_Midnight_Torii_Shamisen.mp3' },
  { id: 'track-36', title: 'Glowing Bamboo Sanctuary', genre: 'japanese', fileName: '036_Glowing_Bamboo_Sanctuary.mp3' },
  { id: 'track-37', title: 'Stone Steps at Moonrise', genre: 'japanese', fileName: '037_Stone_Steps_at_Moonrise.mp3' },
  { id: 'track-38', title: 'Silver Pagoda Dream', genre: 'japanese', fileName: '038_Silver_Pagoda_Dream.mp3' },
  { id: 'track-39', title: 'Bamboo Corridor Groove', genre: 'japanese', fileName: '039_Bamboo_Corridor_Groove.mp3' },
  { id: 'track-40', title: 'Fox Shrine Nocturne', genre: 'japanese', fileName: '040_Fox_Shrine_Nocturne.mp3' },
  { id: 'track-41', title: 'Starlit Shrine Courtyard', genre: 'japanese', fileName: '041_Starlit_Shrine_Courtyard.mp3' },
  { id: 'track-42', title: 'Misty Bamboo Moon', genre: 'japanese', fileName: '042_Misty_Bamboo_Moon.mp3' },
  { id: 'track-43', title: 'Afterglow of the Festival', genre: 'japanese', fileName: '043_Afterglow_of_the_Festival.mp3' },
  { id: 'track-44', title: 'Blue Moon Forest Shrine', genre: 'japanese', fileName: '044_Blue_Moon_Forest_Shrine.mp3' },
  { id: 'track-45', title: 'Dawn Beyond Bamboo', genre: 'japanese', fileName: '045_Dawn_Beyond_Bamboo.mp3' },
  { id: 'track-86', title: 'Torii in Moonlight', genre: 'japanese', fileName: '086_Torii_in_Moonlight.mp3' },
  { id: 'track-87', title: 'Moonlight on the Bamboo Path', genre: 'japanese', fileName: '087_Moonlight_on_the_Bamboo_Path.mp3' },
  { id: 'track-88', title: 'In the Lantern Courtyard', genre: 'japanese', fileName: '088_In_the_Lantern_Courtyard.mp3' },
  { id: 'track-89', title: 'Breathing in Bamboo Shadows', genre: 'japanese', fileName: '089_Breathing_in_Bamboo_Shadows.mp3' },
  { id: 'track-90', title: 'Steps Awaiting the Moon', genre: 'japanese', fileName: '090_Steps_Awaiting_the_Moon.mp3' },
  { id: 'track-91', title: 'Quiet Waltz at the Bamboo Pavilion', genre: 'japanese', fileName: '091_Quiet_Waltz_at_the_Bamboo_Pavilion.mp3' },
  { id: 'track-92', title: 'Lanterns Reflected in the Shrine Pond', genre: 'japanese', fileName: '092_Lanterns_Reflected_in_the_Shrine_Pond.mp3' },
  { id: 'track-93', title: 'Bamboo Gate at Midnight', genre: 'japanese', fileName: '093_Bamboo_Gate_at_Midnight.mp3' },
  { id: 'track-94', title: 'Moonlit Veranda', genre: 'japanese', fileName: '094_Moonlit_Veranda.mp3' },
  { id: 'track-95', title: 'Moon Above Bamboo Leaves', genre: 'japanese', fileName: '095_Moon_Above_Bamboo_Leaves.mp3' },
  { id: 'track-96', title: 'Breeze at the Quiet Shrine', genre: 'japanese', fileName: '096_Breeze_at_the_Quiet_Shrine.mp3' },
  { id: 'track-97', title: 'Silver Bamboo Dew', genre: 'japanese', fileName: '097_Silver_Bamboo_Dew.mp3' },
  { id: 'track-98', title: 'Starlight Beyond the Torii', genre: 'japanese', fileName: '098_Starlight_Beyond_the_Torii.mp3' },
  { id: 'track-99', title: 'Garden Awaiting the Moon', genre: 'japanese', fileName: '099_Garden_Awaiting_the_Moon.mp3' },
  { id: 'track-100', title: 'Pale Light in the Bamboo', genre: 'japanese', fileName: '100_Pale_Light_in_the_Bamboo.mp3' },
  { id: 'track-101', title: 'Reflected Moon on the Shrine Path', genre: 'japanese', fileName: '101_Reflected_Moon_on_the_Shrine_Path.mp3' },
  { id: 'track-102', title: 'Night Breeze and Silver Bells', genre: 'japanese', fileName: '102_Night_Breeze_and_Silver_Bells.mp3' },
  { id: 'track-103', title: 'Moonlight on Mossy Stones', genre: 'japanese', fileName: '103_Moonlight_on_Mossy_Stones.mp3' },
  { id: 'track-104', title: 'Bamboo Shadows Weaving Dreams', genre: 'japanese', fileName: '104_Bamboo_Shadows_Weaving_Dreams.mp3' },
  { id: 'track-105', title: 'Lingering Moonlight', genre: 'japanese', fileName: '105_Lingering_Moonlight.mp3' },
];

export function createTracks(audioBaseUrl: string): Track[] {
  return TRACK_DEFINITIONS.map((track) => ({
    ...track,
    source: `${audioBaseUrl}${track.fileName}`,
  }));
}
